force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>ClassName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Record_id__c.field-meta.xml
<CustomField>
    <fullName>Record_id__c</fullName>
    <label>Record id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/RecordData__c.field-meta.xml
<CustomField>
    <fullName>RecordData__c</fullName>
    <label>RecordData</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExceptionHandler.cls
public class ExceptionHandler {
    
    public static void addLog(Exception ae,String data){
        Error_Log__c err = new Error_Log__c();
        err.LineNumber__c = ae.getLineNumber();
        err.Message__c = ae.getMessage();
        err.StackTrace__c = ae.getStackTraceString();
        err.Type__c = ae.getTypeName();
        err.User__c = UserInfo.getUserId();
        err.RecordData__c = data;
        database.insert(err,false);  
    }
      public static void addLog(Exception ae,String data,string className,string recordId){
        Error_Log__c err = new Error_Log__c();
        err.LineNumber__c = ae.getLineNumber();
        err.Message__c = ae.getMessage();
        err.StackTrace__c = ae.getStackTraceString();
        err.Type__c = ae.getTypeName();
        err.User__c = UserInfo.getUserId();
        err.RecordData__c = data;
          err.className__c =className;
          err.Record_Id__c =recordId;
        database.insert(err,false);  
    }
    public static void addLog(Integer line,String msg,String str,String typ,String data){
        Error_Log__c err = new Error_Log__c();
        err.LineNumber__c = line;
        err.Message__c = msg;
        err.StackTrace__c = str;
        err.Type__c = typ;
        err.User__c = UserInfo.getUserId();
        err.RecordData__c = data;
        database.insert(err,false);  
    }
    public static void addLog(Exception ae){
        Error_Log__c err = new Error_Log__c();
        err.LineNumber__c = ae.getLineNumber();
        err.Message__c = ae.getMessage();
        err.StackTrace__c = ae.getStackTraceString();
        err.Type__c = ae.getTypeName();
        err.User__c = UserInfo.getUserId();
        database.insert(err,false);  
    }
    
}