force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <displayFormat>sh-{0000}</displayFormat>
        <label>Shipping Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Same_as_BillingAddress__c.field-meta.xml
<CustomField>
    <fullName>Same_as_BillingAddress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Same as BillingAddress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ShippingAddressHandler.cls
public class ShippingAddressHandler {

    public static void populateBillingAddress(List<Shipping_Address__c> records) {

        Set<Id> accountIds = new Set<Id>();

        // Collect Account Ids
        for (Shipping_Address__c ship : records) {
            if (ship.Same_as_BillingAddress__c == true && ship.Account__c != null) {
                accountIds.add(ship.Account__c);
            }
        }

        if (accountIds.isEmpty()) {
            return;
        }

        // Query Accounts in bulk
        Map<Id, Account> accMap = new Map<Id, Account>(
    [SELECT Id,
            BillingStreet,
            BillingCity,
            BillingPostalCode,
            BillingStateCode,
            BillingCountryCode
     FROM Account
     WHERE Id IN :accountIds]
);

        // Assign Billing to Shipping Address
        for (Shipping_Address__c ship : records) {

            if (ship.Same_as_BillingAddress__c == true
                && ship.Account__c != null
                && accMap.containsKey(ship.Account__c)) {

                Account acc = accMap.get(ship.Account__c);

               ship.Address__Street__s      = acc.BillingStreet;
                ship.Address__City__s        = acc.BillingCity;
                ship.Address__StateCode__s   = acc.BillingStateCode;
                ship.Address__CountryCode__s = acc.BillingCountryCode;
                ship.Address__PostalCode__s  = acc.BillingPostalCode;

            }
        }
    }
}