force-app/main/default/objects/General_Settings__c/General_Settings__c.object-meta.xml
<CustomObject>
    <label>General Setting</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>General Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Settings__c/fields/Academy_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Academy_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Academy Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Campaign_Expense_Approver__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Expense_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Expense Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Campaign_Final_Approver__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Final_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Final Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Campaign_Marketing_Manager_Approver__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Marketing_Manager_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Marketing Manager Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_SettingsLdNJ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Digital_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Digital_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Digital Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/HR_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>HR_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HR Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Marketing_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Sales_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Sales_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Service_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Service_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Telephony_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Telephony_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Telephony Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CampaignTrigger_Handler.cls
public class CampaignTrigger_Handler {
    /**************************************************************** 
* Class Name  : CampaignTrigger_Handler  @Company  : Fingertip    @Created Date  : 21-9-2025  
@description : campaign object trigger handler   @author  :Nanma T V   @User By  : - campagin trigger 
* Change Log: 
* ----------------------------------------------------------------------------- 
* Ver |   Author      |   Date        |   Description 
* ----------------------------------------------------------------------------- 
* 1.0 |   Nanma  |  21-9-2025 |   Initial version      
* -------------------------------------------------------------------
**************************************************************** */
    
    
    /*@method name :campaignSubmitterNotification   @description :trigger  notification after  campagin approved /rejected @lastModified: 21/9/2025 @param1: campaign list @param 2: status : approved /rejected*/
    public static void campaignSubmitterNotification( list<Campaign> apprRejectCampaignList,string status ){
        CustomNotificationType type = [SELECT Id FROM CustomNotificationType WHERE DeveloperName =: 'Campaign_Notification' LIMIT 1];
        String body, title, senderId, notificationId;
        notificationId = type.Id;
        senderId = UserInfo.getUserId();
        for (Campaign camp : apprRejectCampaignList) {
            body = 'Campaign-' + camp.Name + ' has been '+status;
            title = camp.Name+' - '+status;
            // Send notification to owner
            Set<String> recUserIds = new Set<String>{camp.OwnerId};
                SendEmailCustomNotification.sendNotification(body, title, senderId, notificationId, camp.Id, recUserIds);
        } 
    }  
      @TestVisible
      public static Boolean skipInTest = false;
    
    public static void mapApproverUser(list<Campaign> campaignList){
         if (Test.isRunningTest() && skipInTest) {
        return;
          }
        General_Settings__c settings =[select Id, Campaign_Marketing_Manager_Approver__c, Campaign_Final_Approver__c, 
                                       Campaign_Expense_Approver__c, Telephony_Campaign_Approver__c, Academy_Campaign_Approver__c, 
                                       Sales_Campaign_Approver__c, Service_Campaign_Approver__c, Marketing_Campaign_Approver__c, 
                                       HR_Campaign_Approver__c, Digital_Campaign_Approver__c from General_Settings__c limit 1];  
        for(Campaign camp : campaignList){ 

            if(settings.Campaign_Marketing_Manager_Approver__c !=null){
                camp.Marketing_Manager_Approver__c = settings.Campaign_Marketing_Manager_Approver__c;
            }
            if(camp.Budget_Source__c == 'Marketing' || camp.Budget_Source__c == 'Corporate'){
                camp.Budget_Holder_Approver__c = settings.Marketing_Campaign_Approver__c;
            }else if(camp.Budget_Source__c == 'Digital'){
                camp.Budget_Holder_Approver__c = settings.Digital_Campaign_Approver__c;
            }else if(camp.Budget_Source__c == 'HR' || camp.Budget_Source__c == 'Others'){
                camp.Budget_Holder_Approver__c = settings.HR_Campaign_Approver__c;
            }else if(camp.Budget_Source__c == 'Sales'){
                camp.Budget_Holder_Approver__c = settings.Sales_Campaign_Approver__c;
            }else if(camp.Budget_Source__c == 'Service Sales'){
                camp.Budget_Holder_Approver__c = settings.Service_Campaign_Approver__c;
            }else if(camp.Budget_Source__c == 'Academy'){
                camp.Budget_Holder_Approver__c = settings.Academy_Campaign_Approver__c;
            }else if(camp.Budget_Source__c == 'Telephony'){
                camp.Budget_Holder_Approver__c = settings.Telephony_Campaign_Approver__c;
            }
               if(settings.Campaign_Expense_Approver__c !=null){
                camp.Final_Expense_Approver__c = settings.Campaign_Expense_Approver__c;
            }
               if(settings.Campaign_Final_Approver__c !=null){
                camp.Campaign_Final_Approver__c = settings.Campaign_Final_Approver__c;
            }
        }
    } 
}