force-app/main/default/objects/Expenses_Line_Item__c/Expenses_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Expenses Line Item</label>
    <nameField>
        <displayFormat>EXP DAY - {00000}</displayFormat>
        <label>Expenses_Line_Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenses_Line_Item__c/fields/localId__c.field-meta.xml
<CustomField>
    <fullName>localId__c</fullName>
    <label>localId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExpenseLineItemTriggerHandler.cls
public class ExpenseLineItemTriggerHandler {
    public static void afterInsert(List<Expenses_Line_Item__c> newExpenseItems) {
        Set<String> uniqueFileIds = new Set<String>();
        Map<String, Id> expItemIdMap = new Map<String, Id>();

        // Collect all unique file IDs from new accounts
        for (Expenses_Line_Item__c expItem : newExpenseItems) {
            if (expItem.localId__c != null) {
                uniqueFileIds.add(expItem.localId__c);
                expItemIdMap.put(expItem.localId__c, expItem.Id);
            }
        }
        
        if (!uniqueFileIds.isEmpty()) {
            // Query files with matching unique IDs
            List<ContentDocument> files = [
                SELECT Id, Description 
                FROM ContentDocument 
                WHERE Description IN :uniqueFileIds
            ];
            system.debug('files'+files);
            
            List<ContentDocumentLink> fileLinks = new List<ContentDocumentLink>();
            // Link each file to the correct account
            for (ContentDocument file : files) {
                if (expItemIdMap.containsKey(file.Description)) {
                    ContentDocumentLink link = new ContentDocumentLink();
                    link.ContentDocumentId = file.Id;
                    link.LinkedEntityId = expItemIdMap.get(file.Description);
                    link.ShareType = 'V';
                    link.Visibility = 'AllUsers';
                    fileLinks.add(link);
                }
            }
            
            if (!fileLinks.isEmpty()) {
                insert fileLinks;
            }
        }
        
    }
}