force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Log</label>
    <nameField>
        <displayFormat>Log -{00000}</displayFormat>
        <label>Dailylog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Day_started_Time__c.field-meta.xml
<CustomField>
    <fullName>Day_started_Time__c</fullName>
    <description>Information about the start time</description>
    <label>Day started Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/KMs_Travelled__c.field-meta.xml
<CustomField>
    <fullName>KMs_Travelled__c</fullName>
    <label>Kilometres Travelled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_of_Transport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Expense_Approver_L1__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approver_L1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Expenses3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <description>Type of expenses being claimed.</description>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Accommodation</fullName>
            </value>
            <value>
                <fullName>Daily Allowance</fullName>
            </value>
            <value>
                <fullName>Food Allowance</fullName>
            </value>
            <value>
                <fullName>Printing charges</fullName>
            </value>
            <value>
                <fullName>Stationary charges</fullName>
            </value>
            <value>
                <fullName>Courier chargers</fullName>
            </value>
            <value>
                <fullName>others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expenses_Line_Item__c/Expenses_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Expenses Line Item</label>
    <nameField>
        <displayFormat>EXP DAY - {00000}</displayFormat>
        <label>Expenses_Line_Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenses_Line_Item__c/fields/Daily_Log__c.field-meta.xml
<CustomField>
    <fullName>Daily_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Log</label>
    <referenceTo>Daily_Log__c</referenceTo>
    <relationshipLabel>Expense Line Items</relationshipLabel>
    <relationshipName>Expense_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenses_Line_Item__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>Expenses_line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expenses_Line_Item__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expenses_Line_Item__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expense_Type2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/General_Settings__c/General_Settings__c.object-meta.xml
<CustomObject>
    <label>General Setting</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>General Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Settings__c/fields/Academy_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Academy_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Academy Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Campaign_Expense_Approver__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Expense_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Expense Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Campaign_Final_Approver__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Final_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Final Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Campaign_Marketing_Manager_Approver__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Marketing_Manager_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Marketing Manager Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_SettingsLdNJ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Digital_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Digital_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Digital Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Expense_Level_1_Approver__c.field-meta.xml
<CustomField>
    <fullName>Expense_Level_1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Level 1 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Expense_Level_2_Approver__c.field-meta.xml
<CustomField>
    <fullName>Expense_Level_2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Level 2 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settingsr68A</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/HR_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>HR_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HR Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Marketing_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Sales_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Sales_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Service_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Service_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Telephony_Campaign_Approver__c.field-meta.xml
<CustomField>
    <fullName>Telephony_Campaign_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Telephony Campaign Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/Travel_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Travel Eligibility</label>
    <nameField>
        <displayFormat>TA{0000}</displayFormat>
        <label>Travel_Eligibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Eligibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Eligibility__c/fields/Conveyance_Allowance_per_KM_Bike__c.field-meta.xml
<CustomField>
    <fullName>Conveyance_Allowance_per_KM_Bike__c</fullName>
    <label>TA Per KM Charges :  Bike</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/Conveyance_Allowance_per_KM_Own_Car__c.field-meta.xml
<CustomField>
    <fullName>Conveyance_Allowance_per_KM_Own_Car__c</fullName>
    <label>TA Per KM Charges :  Car</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/DA_Other_District__c.field-meta.xml
<CustomField>
    <fullName>DA_Other_District__c</fullName>
    <label>DA Other District</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/DA_Other_State__c.field-meta.xml
<CustomField>
    <fullName>DA_Other_State__c</fullName>
    <label>DA Other State</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/Daily_Allowance_HQ__c.field-meta.xml
<CustomField>
    <fullName>Daily_Allowance_HQ__c</fullName>
    <label>DA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/Eligibility_For__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_For__c</fullName>
    <label>Eligibility For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Band</fullName>
                <default>true</default>
                <label>Band</label>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Profile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/Travel_Mode_HQ__c.field-meta.xml
<CustomField>
    <fullName>Travel_Mode_HQ__c</fullName>
    <label>Travel Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_of_Transport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Eligibility__c/fields/Travel_Mode_UC__c.field-meta.xml
<CustomField>
    <fullName>Travel_Mode_UC__c</fullName>
    <label>Travel Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_of_Transport</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Expense_Type2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DA</fullName>
    </customValue>
    <customValue>
        <fullName>TA</fullName>
    </customValue>
    <customValue>
        <fullName>Accommodation</fullName>
    </customValue>
    <customValue>
        <fullName>Food Allowance</fullName>
    </customValue>
    <customValue>
        <fullName>Printing Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Stationary Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Courier Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Other/MISC</fullName>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
        <isActive>false</isActive>
        <label>Travel</label>
    </customValue>
    <customValue>
        <fullName>Transport Conveyance</fullName>
        <isActive>false</isActive>
        <label>Transport Conveyance</label>
    </customValue>
    <customValue>
        <fullName>Mobile Charges</fullName>
        <isActive>false</isActive>
        <label>Mobile Charges</label>
    </customValue>
    <customValue>
        <fullName>Local Conveyance</fullName>
        <isActive>false</isActive>
        <label>Local Conveyance</label>
    </customValue>
    <customValue>
        <fullName>Lodging</fullName>
        <isActive>false</isActive>
        <label>Lodging</label>
    </customValue>
    <customValue>
        <fullName>Daily Allowance</fullName>
        <isActive>false</isActive>
        <label>Daily Allowance</label>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
        <isActive>false</isActive>
        <label>Food</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Expense Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Mode_of_Transport.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Autorishaw</fullName>
    </customValue>
    <customValue>
        <fullName>Bike</fullName>
    </customValue>
    <customValue>
        <fullName>Bus</fullName>
    </customValue>
    <customValue>
        <fullName>Car</fullName>
    </customValue>
    <customValue>
        <fullName>Flight</fullName>
    </customValue>
    <customValue>
        <fullName>Taxi</fullName>
    </customValue>
    <customValue>
        <fullName>Train</fullName>
    </customValue>
    <masterLabel>Mode of Transport</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Profile.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASM</fullName>
    </customValue>
    <customValue>
        <fullName>AVP</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>System Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>TSM</fullName>
    </customValue>
    <customValue>
        <fullName>VP</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Executive</fullName>
        <isActive>false</isActive>
        <label>Sales Executive</label>
    </customValue>
    <customValue>
        <fullName>PT1</fullName>
        <isActive>false</isActive>
        <label>PT1</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <isActive>false</isActive>
        <label>HR</label>
    </customValue>
    <customValue>
        <fullName>Finance Department</fullName>
        <isActive>false</isActive>
        <label>Finance Department</label>
    </customValue>
    <masterLabel>Profile</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExpenseControllerTest.cls
@IsTest
public class ExpenseControllerTest {
    
    @TestSetup
    static void setupTestData() {
        // Create test user with manager
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User manager = new User(
            Alias = 'manager',
            Email = 'manager@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Manager',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'manager@test.example.com'
        );
        insert manager;
        
        User testUser = new User(
            Alias = 'testusr',
            Email = 'testuser@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'TestUser',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'testuser55@test.example.com',
            ManagerId = manager.Id,
     
            Expense_Back_Day_Entry_Limit__c = 7
        );
        insert testUser;
        
           General_Settings__c general = new General_Settings__c(
           
            Campaign_Marketing_Manager_Approver__c = UserInfo.getUserId(),
            Campaign_Final_Approver__c = UserInfo.getUserId(),
            Campaign_Expense_Approver__c = UserInfo.getUserId(),
            Telephony_Campaign_Approver__c = UserInfo.getUserId(),
            Academy_Campaign_Approver__c = UserInfo.getUserId(),
            Sales_Campaign_Approver__c = UserInfo.getUserId(),
            Service_Campaign_Approver__c = UserInfo.getUserId(),
            Marketing_Campaign_Approver__c = UserInfo.getUserId(),
            HR_Campaign_Approver__c = UserInfo.getUserId(),
            Digital_Campaign_Approver__c = UserInfo.getUserId(),
               Expense_Level_1_Approver__c= UserInfo.getUserId(),  
               Expense_Level_2_Approver__c= UserInfo.getUserId()
        );
        insert general;
        // Create Travel Eligibility record
        Travel_Eligibility__c eligibility = new Travel_Eligibility__c(
            Eligibility_For__c = 'Profile',
            Profile__c = 'ASM',
            Conveyance_Allowance_per_KM_Bike__c = 5,
            Conveyance_Allowance_per_KM_Own_Car__c = 10,
            Daily_Allowance_HQ__c = 1000,
            DA_Other_State__c = 1500,
            DA_Other_District__c = 1200,
            Travel_Mode_HQ__c = 'Car;Bike;Autorishaw',
            Travel_Mode_UC__c = 'Car;Bike'
        );
        insert eligibility;
        
        // Create Daily Log records
        List<Daily_Log__c> dailyLogs = new List<Daily_Log__c>();
        for (Integer i = 0; i < 5; i++) {
            dailyLogs.add(new Daily_Log__c(
                Day_started_Time__c = Date.today().addDays(i),
                KMs_Travelled__c = 100 + i,
                Mode_of_transport__c = 'Car'
            ));
        }
        insert dailyLogs;
        
        System.runAs(testUser) {
            // Create Expense record
            Expense__c expense = new Expense__c(
                Start_Date__c = Date.today(),
                End_Date__c = Date.today().addDays(30),
                Expense_Type__c = 'Travel',
                Expense_Approver_L1__c = manager.Id
            );
            insert expense;
            
            // Create Expense Line Items
            List<Expenses_Line_Item__c> lineItems = new List<Expenses_Line_Item__c>();
            for (Integer i = 0; i < 3; i++) {
                lineItems.add(new Expenses_Line_Item__c(
                    Expense__c = expense.Id,
                    Expense_Date__c = Date.today().addDays(i),
                    Expense_Type__c = 'TA',
                    Travel_Type__c = 'In Office',
                    Travel_Mode__c = 'Car',
                    Amount__c = 500 + (i * 100),
                    Total_KM__c = 50 + i,
                    Approval_Status__c = 'Draft',
                    localId__c = 'test-local-' + i
                ));
            }
            insert lineItems;
        }
    }
    
    @IsTest
    static void testGetExpensesWithRecordId() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        Expense__c testExpense = [SELECT Id FROM Expense__c  LIMIT 1];
        
        Test.startTest();
        System.runAs(testUser) {
            ExpenseController.ExpenseData result = ExpenseController.getExpenses(testExpense.Id);
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testGetExpensesWithoutRecordId() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        
        Test.startTest();
        System.runAs(testUser) {
            ExpenseController.ExpenseData result = ExpenseController.getExpenses(null);
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testGetExpensesWithNoExistingExpense() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        // Delete existing expense to test creation path
        delete [SELECT Id FROM Expense__c];
        
        Test.startTest();
        System.runAs(testUser) {
            ExpenseController.ExpenseData result = ExpenseController.getExpenses(null);
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testGetPicklistValues() {
        Test.startTest();
        List<String> picklistValues = ExpenseController.getPicklistValues('Expenses_Line_Item__c', 'Travel_Mode__c');
        Test.stopTest();
    }
    
    @IsTest
    static void testValidateFilesWithDocIds() {
        // Create test content
        ContentVersion cv = new ContentVersion(
            Title = 'Test Document',
            PathOnClient = 'TestDocument.pdf',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert cv;
        
        ContentVersion contentVersion = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
        
        Expense__c testExpense = [SELECT Id FROM Expense__c LIMIT 1];
        
        // Link document to expense
        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = testExpense.Id,
            ContentDocumentId = contentVersion.ContentDocumentId,
            ShareType = 'V'
        );
        insert cdl;
        
        List<Map<String, String>> itemsToCheck = new List<Map<String, String>>{
            new Map<String, String>{
                'uniqueKey' => 'test1',
                    'Id' => testExpense.Id
                    }
        };
        
        Test.startTest();
        Map<String, Boolean> results = ExpenseController.validateFiles(itemsToCheck);
        Test.stopTest();
    }
    
    @IsTest
    static void testValidateFilesWithLocalIds() {
        ContentVersion cv = new ContentVersion(
            Title = 'Test Document',
            PathOnClient = 'TestDocument.pdf',
            VersionData = Blob.valueOf('Test Content'),
            Description = 'test-local-0',
            IsMajorVersion = true
        );
        insert cv;
        
        List<Map<String, String>> itemsToCheck = new List<Map<String, String>>{
            new Map<String, String>{
                'uniqueKey' => 'test2',
                    'localId__c' => 'test-local-0'
                    }
        };
        
        Test.startTest();
        Map<String, Boolean> results = ExpenseController.validateFiles(itemsToCheck);
        Test.stopTest();
    }
    
    @IsTest
    static void testValidateFilesEmptyList() {
        Test.startTest();
        Map<String, Boolean> results = ExpenseController.validateFiles(new List<Map<String, String>>());
        Test.stopTest();
    }
    
    @IsTest
    static void testSaveExpenseCreateNew() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        
        System.runAs(testUser) {
            // Delete existing expense to test creation
            delete [SELECT Id FROM Expense__c];
            
            Expense__c newExpense = new Expense__c(
                Start_Date__c = Date.today(),
                End_Date__c = Date.today().addDays(30)
            );
            
            List<Expenses_Line_Item__c> lineItems = new List<Expenses_Line_Item__c>{
                new Expenses_Line_Item__c(
                    localId__c = 'new-item-1',
                    Expense_Date__c = Date.today(),
                    Expense_Type__c = 'TA',
                    Travel_Type__c = 'In Office',
                    Travel_Mode__c = 'Car',
                    Amount__c = 1000,
                    Approval_Status__c = 'Draft',
                    Is_Updated__c = true
                )
            };
            
            Test.startTest();
            ExpenseController.ExpenseData result = ExpenseController.saveExpense(
                newExpense, 
                lineItems, 
                new List<String>(), 
                false, 
                false, 
                false,
                ''
            );
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testSaveExpenseUpdateExisting() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        Expense__c existingExpense = [SELECT Id, Name FROM Expense__c LIMIT 1];
         List<Expenses_Line_Item__c> existingItems = [SELECT Id,Food_Type__c,Approval_Status__c,System_Calculated_Amount__c,Local_Conveyance_Limit__c,lodging_Limit__c,Calculated_KM__c,Amount__c,Remarks__c, DA_Limit__c,Total_Distance_Calculated_by_ODM_Reading__c,Total_KM__c,TA_Limit__c,Working_Hours__c,Daily_Log__c,Accommodation_Type__c,Travel_Mode__c,Expense_Type__c,Is_Updated__c,localId__c,Expense_Date__c,Travel_Type__c FROM Expenses_Line_Item__c];
        
        System.runAs(testUser) {
            List<Expenses_Line_Item__c> updatedItems = new List<Expenses_Line_Item__c>();
            for (Expenses_Line_Item__c item : existingItems) {
                item.Amount__c = 600;
                item.Is_Updated__c = true;
                updatedItems.add(item);
            }
            
            Test.startTest();
            ExpenseController.ExpenseData result = ExpenseController.saveExpense(
                existingExpense, 
                updatedItems, 
                new List<String>(), 
                false, 
                false, 
                false,
                ''
            );
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testSaveExpenseWithDelete() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        Expense__c existingExpense = [SELECT Id, Name FROM Expense__c LIMIT 1];
        List<Expenses_Line_Item__c> existingItems = [SELECT Id FROM Expenses_Line_Item__c];
        
        System.runAs(testUser) {
            List<String> itemsToDelete = new List<String>{existingItems[0].Id};
                
                Test.startTest();
            ExpenseController.ExpenseData result = ExpenseController.saveExpense(
                existingExpense, 
                new List<Expenses_Line_Item__c>(), 
                itemsToDelete, 
                false, 
                false, 
                false,
                ''
            );
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testSaveExpenseSubmitForApproval() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        Expense__c existingExpense = [SELECT Id, Name FROM Expense__c LIMIT 1];
        List<Expenses_Line_Item__c> existingItems = [SELECT Id,Food_Type__c,Approval_Status__c,System_Calculated_Amount__c,Local_Conveyance_Limit__c,lodging_Limit__c,Calculated_KM__c,Amount__c,Remarks__c, DA_Limit__c,Total_Distance_Calculated_by_ODM_Reading__c,Total_KM__c,TA_Limit__c,Working_Hours__c,Daily_Log__c,Accommodation_Type__c,Travel_Mode__c,Expense_Type__c,Is_Updated__c,localId__c,Expense_Date__c,Travel_Type__c FROM Expenses_Line_Item__c];
          
        System.runAs(testUser) {
            List<Expenses_Line_Item__c> updatedItems = new List<Expenses_Line_Item__c>();
            for (Expenses_Line_Item__c item : existingItems) {
                item.Approval_Status__c = 'Pending';
                item.Is_Updated__c = true;
                updatedItems.add(item);
            }
            
            Test.startTest();
            ExpenseController.ExpenseData result = ExpenseController.saveExpense(
                existingExpense, 
                updatedItems, 
                new List<String>(), 
                true, 
                false, 
                false,
                'Please approve'
            );
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testSaveExpenseApproveRecord() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        Expense__c existingExpense = [SELECT Id, Name FROM Expense__c LIMIT 1];
        List<Expenses_Line_Item__c> existingItems = [SELECT Id,Food_Type__c,Approval_Status__c,System_Calculated_Amount__c,Local_Conveyance_Limit__c,lodging_Limit__c,Calculated_KM__c,Amount__c,Remarks__c, DA_Limit__c,Total_Distance_Calculated_by_ODM_Reading__c,Total_KM__c,TA_Limit__c,Working_Hours__c,Daily_Log__c,Accommodation_Type__c,Travel_Mode__c,Expense_Type__c,Is_Updated__c,localId__c,Expense_Date__c,Travel_Type__c FROM Expenses_Line_Item__c];
        
        System.runAs(testUser) {
            Test.startTest();
            ExpenseController.ExpenseData result = ExpenseController.saveExpense(
                existingExpense, 
                existingItems, 
                new List<String>(), 
                false, 
                true, 
                false,
                'Approved'
            );
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testSaveExpenseRejectRecord() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'testuser55@test.example.com' LIMIT 1];
        Expense__c existingExpense = [SELECT Id, Name FROM Expense__c LIMIT 1];
         List<Expenses_Line_Item__c> existingItems = [SELECT Id,Food_Type__c,Approval_Status__c,System_Calculated_Amount__c,Local_Conveyance_Limit__c,lodging_Limit__c,Calculated_KM__c,Amount__c,Remarks__c, DA_Limit__c,Total_Distance_Calculated_by_ODM_Reading__c,Total_KM__c,TA_Limit__c,Working_Hours__c,Daily_Log__c,Accommodation_Type__c,Travel_Mode__c,Expense_Type__c,Is_Updated__c,localId__c,Expense_Date__c,Travel_Type__c FROM Expenses_Line_Item__c];
        
        System.runAs(testUser) {
            Test.startTest();
            ExpenseController.ExpenseData result = ExpenseController.saveExpense(
                existingExpense, 
                existingItems, 
                new List<String>(), 
                false, 
                false, 
                true,
                'Rejected: Missing details'
            );
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testSaveExpenseWithNullExpense() {
        Test.startTest();
        ExpenseController.ExpenseData result = ExpenseController.saveExpense(
            null, 
            new List<Expenses_Line_Item__c>(), 
            new List<String>(), 
            false, 
            false, 
            false,
            ''
        );
        Test.stopTest();
    }
    
    @IsTest
    static void testGetMonthName() {
        Test.startTest();
        String jan = ExpenseController.getMonthName(1);
        String feb = ExpenseController.getMonthName(2);
        String mar = ExpenseController.getMonthName(3);
        String apr = ExpenseController.getMonthName(4);
        String may = ExpenseController.getMonthName(5);
        String jun = ExpenseController.getMonthName(6);
        String jul = ExpenseController.getMonthName(7);
        String aug = ExpenseController.getMonthName(8);
        String sep = ExpenseController.getMonthName(9);
        String oct = ExpenseController.getMonthName(10);
        String nov = ExpenseController.getMonthName(11);
        String dec = ExpenseController.getMonthName(12);
        Test.stopTest();
    }
    
    @IsTest
    static void testSkipHeavyLogicFlag() {
        Test.startTest();
        ExpenseController.skipHeavyLogic = true;
        Boolean flag = ExpenseController.skipHeavyLogic;
        Test.stopTest();
    }
    
    @IsTest
    static void testExpenseDataInnerClass() {
        Test.startTest();
        ExpenseController.ExpenseData data = new ExpenseController.ExpenseData();
        data.LoggedInUser = new User(FirstName = 'Test', LastName = 'User');
        data.selectedUser = new User(FirstName = 'Selected', LastName = 'User');
        data.expense = new Expense__c(Name = 'Test Expense');
        data.lineItems = new List<Expenses_Line_Item__c>();
        data.days = new List<Daily_Log__c>();
        data.eligibilities = new Travel_Eligibility__c();
        data.travelTypes = new List<String>{'Local', 'Outstation'};
        data.travelModes = new List<String>{'Car', 'Bike'};
        data.expenseTypes = new List<String>{'TA', 'DA'};
        data.accomodationTypes = new List<String>{'Hotel', 'Guest House'};
        data.foodTypes = new List<String>{'Breakfast', 'Lunch'};
        data.approvalStatus = new List<String>{'Draft', 'Pending'};
        data.startDate = Date.today();
        data.endDate = Date.today().addDays(30);
        data.isCurrentUserApprover = true;
        data.approverId = UserInfo.getUserId();
        data.isDistrictInCharge = false;
        data.expenseId = 'test-id';
        data.expenseCommnents = 'Test comments';
        data.isCarEnabled = true;
        data.isBikeEnabled = true;
        data.isAutoEnabled = false;
        Test.stopTest();
    }
}