force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Log</label>
    <nameField>
        <displayFormat>Log -{00000}</displayFormat>
        <label>Dailylog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Distance_by_SF__c.field-meta.xml
<CustomField>
    <fullName>Distance_by_SF__c</fullName>
    <label>Distance by SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Distance_Calculated_by_SF__c.field-meta.xml
<CustomField>
    <fullName>Distance_Calculated_by_SF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Distance Calculated by SF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/KMs_Travelled__c.field-meta.xml
<CustomField>
    <fullName>KMs_Travelled__c</fullName>
    <label>Kilometres Travelled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Last_visit_distance__c.field-meta.xml
<CustomField>
    <fullName>Last_visit_distance__c</fullName>
    <label>Last visit distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Last_Visit_Distance_SF__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Distance_SF__c</fullName>
    <label>Last Visit Distance SF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>log-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Log</relationshipLabel>
    <relationshipName>Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Daily_Log__c.field-meta.xml
<CustomField>
    <fullName>Daily_Log__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Daily Log</label>
    <referenceTo>Daily_Log__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance (Google)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Distance_Calculated_by_Google_API__c.field-meta.xml
<CustomField>
    <fullName>Distance_Calculated_by_Google_API__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Distance Calculated by Google API</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Distance_Calculated_by_SF__c.field-meta.xml
<CustomField>
    <fullName>Distance_Calculated_by_SF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Distance Calculated by SF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/SF_Distance__c.field-meta.xml
<CustomField>
    <fullName>SF_Distance__c</fullName>
    <label>SF Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_for__c.field-meta.xml
<CustomField>
    <fullName>Visit_for__c</fullName>
    <label>Visit for</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Start__c.field-meta.xml
<CustomField>
    <fullName>Visit_Start__c</fullName>
    <label>Visit Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CalculateDistanceAPI.cls
public class CalculateDistanceAPI {
    /**************************************************************** 
* Class Name  : CalculateDistanceAPI  @Company  : Fingertip    @Created Date  : 29-9-2025  
@description : CalculateDISTANCE USING GOOGLE API   @author  :Nanma T V   @User By  : -visitrigger
* Change Log: 
* ----------------------------------------------------------------------------- 
* Ver |   Author      |   Date        |   Description 
* ----------------------------------------------------------------------------- 
* 1.0 |   Nanma  |  05-01-2025 |   Initial version      
* -------------------------------------------------------------------*/
    
    /*@methodName:distanceCalculation API call @param1:dailylogIds @des : visit calculation*/
    @future(callout=true)
    public static void distanceCalculation(List<String> dailyLogIds){
        list<log__c> logs= new list<log__c>();
        list<Daily_Log__c> dailylogsToUpdate= new list<Daily_Log__c>();
        list<Visit__c> visitsToUpdate= new list<Visit__c>();
        map<Id,Daily_Log__c> dailylogMap = new  map<Id,Daily_Log__c>([select Id,KMs_Travelled__c,Last_visit_distance__c,Distance_Calculated_by_Google_API__c,Clock_In_Location__Latitude__s,Clock_In_Location__Longitude__s,
                                                                      Clock_Out_Location__Latitude__s,Clock_Out_Location__Longitude__s,
                                                                      (select Id, Name, Visit_Start__c, Visit_for__c, Lead__c, Account__c,
                                                                       Check_In_Location__Latitude__s, Check_In_Location__Longitude__s, Distance__c, 
                                                                       OwnerId, Daily_Log__c,Distance_Calculated_by_Google_API__c  from Visits__r where Status__c!='Planned' and Status__c!='Missed' order by Visit_Start__c asc ) from Daily_Log__c WHERE Id IN :dailyLogIds order by createddate desc]);
        
        
        for(Daily_Log__c d : dailylogMap.values()){
            integer noOfvisit =d.Visits__r.size();
            distanceValue dis = new distanceValue();
            
            if(noOfvisit != 0 ){
                if(  d.Clock_In_Location__Latitude__s !=null && d.Clock_In_Location__Longitude__s !=null ){ //first vist daily log checkin to first visit chekin
                    Visit__c visit =new Visit__c();
                    visit =d.Visits__r[0];
                    if(visit.Check_In_Location__Latitude__s !=null && visit.Check_In_Location__Longitude__s !=null){
                        dis =distanceCalculationinKM( d.Clock_In_Location__Latitude__s, d.Clock_In_Location__Longitude__s,visit.Check_In_Location__Latitude__s ,visit.Check_In_Location__Longitude__s);
                        visit.Distance__c =dis.distance;
                        visit.Distance_Calculated_by_Google_API__c =true;
                        logs.add(dis.log);
                        visitsToUpdate.add(visit);
                    }
                }
                
                if(noOfvisit >1){ //more than one visit
                    list<Visit__c > visits =new list<Visit__c >();
                    visits =d.Visits__r;
                    for(integer i=1 ; i<noOfvisit;i++ ){
                        
                        system.debug(visits[i].name);
                        if( visits[i].Distance_Calculated_by_Google_API__c  ){
                            continue;
                        }
                        if(visits[i-1].Check_In_Location__Latitude__s !=null && visits[i-1].Check_In_Location__Longitude__s !=null && visits[i].Check_In_Location__Latitude__s !=null && visits[i].Check_In_Location__Longitude__s !=null){
                            dis =distanceCalculationinKM(visits[i-1].Check_In_Location__Latitude__s ,visits[i-1].Check_In_Location__Longitude__s,visits[i].Check_In_Location__Latitude__s ,visits[i].Check_In_Location__Longitude__s );
                            visits[i].Distance__c =dis.distance;
                            visits[i].Distance_Calculated_by_Google_API__c =true;
                            logs.add(dis.log);
                            visitsToUpdate.add(visits[i]);
                        }
                    }
                    
                }
            }
            if(d.Clock_Out_Location__Latitude__s !=null && d.Clock_Out_Location__Longitude__s !=null ){ //completed daily log
                if(noOfvisit >0){ // last visit
                    Visit__c visit =new Visit__c();
                    if(noOfvisit ==1 ){
                        visit =d.Visits__r[0];
                    }else{
                        visit =d.Visits__r[noOfvisit -1];
                    }
                    if(visit.Check_In_Location__Latitude__s !=null && visit.Check_In_Location__Longitude__s !=null){
                        dis =distanceCalculationinKM( visit.Check_In_Location__Latitude__s ,visit.Check_In_Location__Longitude__s,d.Clock_Out_Location__Latitude__s ,d.Clock_Out_Location__Longitude__s );
                        d.Distance_Calculated_by_Google_API__c =true;  
                     //   visit.Distance__c =dis.distance;
                       // visit.Distance_Calculated_by_Google_API__c =true;
                        d.Last_visit_distance__c =dis.distance;
                        dailylogsToUpdate.add(d);
                        logs.add(dis.log);  
                    }
                }else if(noOfvisit ==0){ //no visits distance b/w dailylog
                    if(d.Clock_In_Location__Latitude__s !=null && d.Clock_In_Location__Longitude__s !=null ){
                        dis =distanceCalculationinKM(d.Clock_In_Location__Latitude__s , d.Clock_In_Location__Longitude__s ,d.Clock_Out_Location__Latitude__s ,d.Clock_Out_Location__Longitude__s );
                        d.KMs_Travelled__c =dis.distance;
                        d.Distance_Calculated_by_Google_API__c =true;    
                        d.Last_visit_distance__c =0;
                        dailylogsToUpdate.add(d);
                        logs.add(dis.log); 
                    }
                }
            }
        }
        
        if(dailylogsToUpdate.size() >0){
            update dailylogsToUpdate;
        }
        if(visitsToUpdate.size() >0){
            update visitsToUpdate;
        }
        if(logs.size() > 0){
            database.insert(logs);
        }
        
        
    }
    //Calling Google matrix api to get distance
    public static distanceValue distanceCalculationinKM(decimal l1lat, decimal l1long,decimal  l2lat,decimal l2long){ 
        distanceValue d = new distanceValue();
        d.distance =0;
        log__c log = new log__c();
        string ApiKey = label.GOOGLE_MAPS_API_KEY;
        string url = 'https://maps.googleapis.com/maps/api/distancematrix/json?';   
        url = url + 'origins='+ l1lat+','+ l1long;
        url = url + '&destinations='+ l2lat+','+ l2long;           
        url = url + '&key='+ApiKey;   
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('GET');    
        Http http = new Http();
        log.Request__c  = url;
        if(!test.isrunningtest()){
            HTTPResponse res = http.send(req);
            log.Response__c = res.getBody().tostring() ; 
            distancematrix dm =  (distancematrix)JSON.deserialize(res.getBody(),distancematrix.class);   
            if( ( dm.rows.size() > 0 )&& ( dm.rows[0].elements.size() > 0 )  ){
                d.distance= dm.rows[0].elements[0].distance.value/1000; 
            }   
        }
        log.Status_Message__c='Success';
        d.log =log;
        return d;
    }
    
    public static Decimal calculateHaversineDistance(Decimal lat1, Decimal lon1, Decimal lat2, Decimal lon2){
        // Earth's radius varies from 6356.752 km at the poles to 6378.137 km at the equator
        Double radius = 6371.00;
        Double dLat = toRadians(lat2-lat1);
        Double dLon = toRadians(lon2-lon1);
        Double a = Math.sin(dLat/2) * Math.sin(dLat/2) +
            Math.cos(toRadians(lat1)) * Math.cos(toRadians(lat2)) *
            Math.sin(dLon/2) * Math.sin(dLon/2);
        Double c = 2 * Math.asin(Math.sqrt(a));
        
        double kmToMiles = 0.621371;
        return radius * c * kmToMiles;
    }
    
    private static Double toRadians(Decimal degree){
        return degree * 3.1415926 / 180;
    }
    

    public static void distanceCalculationSF(List<String> dailyLogIds){
        list<log__c> logs= new list<log__c>();
        list<Daily_Log__c> dailylogsToUpdate= new list<Daily_Log__c>();
        list<Visit__c> visitsToUpdate= new list<Visit__c>();
        map<Id,Daily_Log__c> dailylogMap = new  map<Id,Daily_Log__c>([select Id,KMs_Travelled__c,Last_Visit_Distance_SF__c,Distance_by_SF__c,Distance_Calculated_by_SF__c,Clock_In_Location__Latitude__s,Clock_In_Location__Longitude__s,
                                                                      Clock_Out_Location__Latitude__s,Clock_Out_Location__Longitude__s,
                                                                      (select Id, Name, Visit_Start__c, Visit_for__c, Lead__c, Account__c,
                                                                       Check_In_Location__Latitude__s, Check_In_Location__Longitude__s, SF_Distance__c, 
                                                                       OwnerId, Daily_Log__c,Distance_Calculated_by_SF__c  from Visits__r where Status__c!='Planned' and Status__c!='Missed' order by Visit_Start__c asc ) from Daily_Log__c WHERE Id IN :dailyLogIds order by createddate desc]);
        
        
        for(Daily_Log__c d : dailylogMap.values()){
            integer noOfvisit =d.Visits__r.size();
            
            if(noOfvisit != 0 ){
                if(  d.Clock_In_Location__Latitude__s !=null && d.Clock_In_Location__Longitude__s !=null ){ //first vist daily log checkin to first visit chekin
                    Visit__c visit =new Visit__c();
                    visit =d.Visits__r[0];
                    if(visit.Check_In_Location__Latitude__s !=null && visit.Check_In_Location__Longitude__s !=null){
                        visit.SF_Distance__c =calculateHaversineDistance( d.Clock_In_Location__Latitude__s, d.Clock_In_Location__Longitude__s,visit.Check_In_Location__Latitude__s ,visit.Check_In_Location__Longitude__s);
                        visit.Distance_Calculated_by_SF__c =true;
                        visitsToUpdate.add(visit);
                    }
                }
                
                if(noOfvisit >1){ //more than one visit
                    list<Visit__c > visits =new list<Visit__c >();
                    visits =d.Visits__r;
                    for(integer i=1 ; i<noOfvisit;i++ ){
                        
                        system.debug(visits[i].name);
                        if( visits[i].Distance_Calculated_by_SF__c  ){
                            continue;
                        }
                        if(visits[i-1].Check_In_Location__Latitude__s !=null && visits[i-1].Check_In_Location__Longitude__s !=null && visits[i].Check_In_Location__Latitude__s !=null && visits[i].Check_In_Location__Longitude__s !=null){
                             visits[i].SF_Distance__c =calculateHaversineDistance(visits[i-1].Check_In_Location__Latitude__s ,visits[i-1].Check_In_Location__Longitude__s,visits[i].Check_In_Location__Latitude__s ,visits[i].Check_In_Location__Longitude__s );
                            visits[i].Distance_Calculated_by_SF__c =true;
                            visitsToUpdate.add(visits[i]);
                        }
                    }
                    
                }
            }
            if(d.Clock_Out_Location__Latitude__s !=null && d.Clock_Out_Location__Longitude__s !=null ){ //completed daily log
                if(noOfvisit >0){ // last visit
                    Visit__c visit =new Visit__c();
                    if(noOfvisit ==1 ){
                        visit =d.Visits__r[0];
                    }else{
                        visit =d.Visits__r[noOfvisit -1];
                    }
                    if(visit.Check_In_Location__Latitude__s !=null && visit.Check_In_Location__Longitude__s !=null){
                         d.Last_Visit_Distance_SF__c =calculateHaversineDistance( visit.Check_In_Location__Latitude__s ,visit.Check_In_Location__Longitude__s,d.Clock_Out_Location__Latitude__s ,d.Clock_Out_Location__Longitude__s );
                        d.Distance_Calculated_by_SF__c =true;  
                        dailylogsToUpdate.add(d); 
                    }
                }else if(noOfvisit ==0){ //no visits distance b/w dailylog
                    if(d.Clock_In_Location__Latitude__s !=null && d.Clock_In_Location__Longitude__s !=null ){
                         d.Distance_by_SF__c =calculateHaversineDistance(d.Clock_In_Location__Latitude__s , d.Clock_In_Location__Longitude__s ,d.Clock_Out_Location__Latitude__s ,d.Clock_Out_Location__Longitude__s );
                        d.Distance_Calculated_by_SF__c =true;    
                        d.Last_Visit_Distance_SF__c =0;
                        dailylogsToUpdate.add(d);

                    }
                }
            }
        }
        
        if(dailylogsToUpdate.size() >0){
            update dailylogsToUpdate;
        }
        if(visitsToUpdate.size() >0){
            update visitsToUpdate;
        }
        if(logs.size() > 0){
            database.insert(logs);
        }
        
        
    }
    public class distanceValue{  
        public decimal distance; 
        public log__c log;
    }
    public class distancematrix{  
        public List<row> rows;   
    } 
    public class row{ 
        public List<element> elements;
    }
    public class element{ 
        public duration duration;
        public distance distance;
    }
    public class distance{ 
        public  string text;
        public  decimal value; 
    }
    public class duration{ 
        public  string text;
        public  decimal  value; 
    }
    
}