force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Log</label>
    <nameField>
        <displayFormat>Log -{00000}</displayFormat>
        <label>Dailylog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Daily_Log__c.field-meta.xml
<CustomField>
    <fullName>Daily_Log__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Daily Log</label>
    <referenceTo>Daily_Log__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dailylogTriggerHandler.cls
public class dailylogTriggerHandler {
    
    //Update last visit 
       public static void beforeUpdate(List<Daily_Log__c> newDailyLogs, Map<Id, Daily_Log__c> oldDailyLogMap) {
    

    }
    
    
  // calculate distance using metrix api  
      public static void afterUpdate(List<Daily_Log__c> newDailyLogs,map<Id,Daily_Log__c> oldDailyLogMap) {
        list<Id> dailyLogIds = new list<Id>();
        Map<Id, Visit__c> visitMap = new Map<Id, Visit__c>();
        Map<String, Id> dailyLogIdMap = new Map<String, Id>();
        for (Daily_Log__c dl :newDailyLogs) {
            //when ever end day is happening we are storing daily log id
            if ((dl.Clock_Out_Location__Latitude__s != oldDailyLogMap.get(dl.Id).Clock_Out_Location__Latitude__s ||
                dl.Clock_Out_Location__Longitude__s != oldDailyLogMap.get(dl.Id).Clock_Out_Location__Longitude__s)  &&
                (dl.Clock_Out_Location__Latitude__s!=null && dl.Clock_Out_Location__Longitude__s !=null)) 
            {
                dailyLogIds.add(dl.Id);
               
            }
            
        } 
          if(dailyLogIds.size() > 0){
            CalculateDistanceAPI.distanceCalculation(dailyLogIds);  
          } 
      
    }
    
}