force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Log</label>
    <nameField>
        <displayFormat>Log -{00000}</displayFormat>
        <label>Dailylog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Day_started_Time__c.field-meta.xml
<CustomField>
    <fullName>Day_started_Time__c</fullName>
    <description>Information about the start time</description>
    <label>Day started Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Vehicle_Used__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Used__c</fullName>
    <label>Vehicle Used</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal/own</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Public transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Daily_Log__c.field-meta.xml
<CustomField>
    <fullName>Daily_Log__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Daily Log</label>
    <referenceTo>Daily_Log__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Time__c</fullName>
    <label>Planned Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <description>Date when the visit is planned for</description>
    <label>Visit Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_for__c.field-meta.xml
<CustomField>
    <fullName>Visit_for__c</fullName>
    <label>Visit for</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/beatPlannerlwcTest.cls
@IsTest
public class beatPlannerlwcTest {

    // =========================
    // TEST DATA SETUP
    // =========================
    @testSetup
    static void setupData() {

        // Account
        Account acc = new Account(
            Name = 'Test Account',
            Phone = '9999999999',
             Customer_Category__c = 'Dealer'
        );
        insert acc;

        // Lead
        Lead ld = new Lead(
            LastName = 'Test Lead',
            Company = 'Test Company',
            Phone = '8888888888',
            Status = 'Open - Not Contacted'
        );
        insert ld;

        // Visits (NO Name field – auto-number)
        DateTime startTime = DateTime.now();
        Visit__c visitCustomer = new Visit__c(
            Visit_for__c = 'Customer',
            Account__c = acc.Id,
            Status__c = 'Planned',
            Visit_Date__c = Date.today(),
            Planned_Start_Time__c = startTime 
            
        );

        Visit__c visitLead = new Visit__c(
            Visit_for__c = 'Lead',
            Lead__c = ld.Id,
            Status__c = 'Planned',
            Visit_Date__c = Date.today(),
            Planned_Start_Time__c = startTime 
        );

        insert new List<Visit__c>{ visitCustomer, visitLead };

        // Daily Log
        Daily_Log__c log = new Daily_Log__c(
            Day_started_time__c = DateTime.now(),
            Vehicle_Used__c = 'Office'
        );
        insert log;

        // Product
        Product2 prod = new Product2(
            Name = 'Test Product',
            IsActive = true
        );
        insert prod;
    }

    // =========================
    // saveFile()
    // =========================
    @IsTest
    static void testSaveFile() {
        Account acc = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
        String result = beatPlannerlwc.saveFile(
            acc.Id,
            'test.png',
            EncodingUtil.base64Encode(Blob.valueOf('filedata'))
        );
        Test.stopTest();
    }

    // =========================
    // getAllVisitData()
    // =========================
    @IsTest
    static void testGetAllVisitData() {
        Visit__c v = [SELECT Id FROM Visit__c LIMIT 1];

        Test.startTest();
        beatPlannerlwc.data d = beatPlannerlwc.getAllVisitData(v.Id);
         beatPlannerlwc.getBeatPlanData(system.today(), system.today()+1);
         beatPlannerlwc.getVisitData('rr');
        Test.stopTest();
    }

    // =========================
    // getDailyLog()
    // =========================
    @IsTest
    static void testGetDailyLog() {
        Test.startTest();
        beatPlannerlwc.data d = beatPlannerlwc.getDailyLog();
        Test.stopTest();
    }

    // =========================
    // getVisitCreateData()
    // =========================
    @IsTest
    static void testGetVisitCreateData() {
        Test.startTest();
        beatPlannerlwc.data d = beatPlannerlwc.getVisitCreateData();
        Test.stopTest();
    }

    // =========================
    // getProductData()
    // =========================
    @IsTest
    static void testGetProductData() {
        Test.startTest();
        beatPlannerlwc.data d = beatPlannerlwc.getProductData();
        Test.stopTest();
    }

    // =========================
    // searchProducts()
    // =========================
    @IsTest
    static void testSearchProducts() {
        Test.startTest();
        beatPlannerlwc.data d1 = beatPlannerlwc.searchProducts('');
        beatPlannerlwc.data d2 = beatPlannerlwc.searchProducts('Test');
        Test.stopTest();
    }

    // =========================
    // validatePlannedVisitForCustomer – Customer
    // =========================
    @IsTest
    static void testValidatePlannedVisitCustomer() {
        Account acc = [SELECT Id FROM Account LIMIT 1];

        try {
            Test.startTest();
            beatPlannerlwc.validatePlannedVisitForCustomer(
                'Customer',
                acc.Id,
                null
            );
            Test.stopTest();
        } catch (Exception e) {
        }
    }

    // =========================
    // validatePlannedVisitForCustomer – Lead
    // =========================
    @IsTest
    static void testValidatePlannedVisitLead() {
        Lead ld = [SELECT Id FROM Lead LIMIT 1];

        try {
            Test.startTest();
            beatPlannerlwc.validatePlannedVisitForCustomer(
                'Lead',
                null,
                ld.Id
            );
            Test.stopTest();
        } catch (Exception e) {
        }
    }

    // =========================
    // getFiles() + deleteFile()
    // =========================
    @IsTest
    static void testGetAndDeleteFiles() {
        Account acc = [SELECT Id FROM Account LIMIT 1];

        ContentVersion cv = new ContentVersion(
            Title = 'TestDoc',
            PathOnClient = 'TestDoc.txt',
            VersionData = Blob.valueOf('Hello'),
            IsMajorVersion = true
        );
        insert cv;
        
        cv = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = cv.ContentDocumentId,
            LinkedEntityId = acc.Id,
            ShareType = 'V'
        );
        insert cdl;

        Test.startTest();
        List<ContentDocument> docs = beatPlannerlwc.getFiles(acc.Id);
        
        if (!docs.isEmpty()) {
            beatPlannerlwc.deleteFile(docs[0].Id);
        }
        Test.stopTest();
    }
}