force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Log</label>
    <nameField>
        <displayFormat>Log -{00000}</displayFormat>
        <label>Dailylog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Day_started_Time__c.field-meta.xml
<CustomField>
    <fullName>Day_started_Time__c</fullName>
    <description>Information about the start time</description>
    <label>Day started Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DailyLogNotificationBatchTest.cls
@isTest
public class DailyLogNotificationBatchTest 
{
    @isTest
    public static void testDailyLogNotificationBatch()
    {
        list<Daily_Log__c> lstDailyLog = new list <Daily_Log__c>();
        
        for(integer counter = 1 ; counter<=10 ; counter ++)
        {
            Daily_Log__c dg = new Daily_Log__c();
            dg.Day_started_time__c = DateTime.newInstance(2023, 11, 20, 0, 0, 0);
            
            
            lstDailyLog.add(dg);
            
        }
        insert lstDailyLog;
        
      
       
        test.startTest();
 
        
        DailyLogNotificationBatch contactsBatch = new DailyLogNotificationBatch();
        
        database.executeBatch(contactsBatch);
        
        DailyLogNotificationBatchScheduler scheduler = new DailyLogNotificationBatchScheduler();
        String jobId = System.schedule('DailyLogNotificationBatchJob', '0 0 0 * * ?', scheduler);

        
        test.stopTest();
    }

}