force-app/main/default/objects/Map_Sub_Region__c/Map_Sub_Region__c.object-meta.xml
<CustomObject>
    <label>Map Sub Region</label>
    <nameField>
        <label>Sub Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Sub Region</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Sub_Region__c/fields/ASM__c.field-meta.xml
<CustomField>
    <fullName>ASM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Map_Sub_Region</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Map_Sub_Region__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipName>Map_Region_User</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Map_Sub_Region__c/fields/Sales_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Map_Region_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/leadCmpController.cls
public class leadCmpController {
    @auraEnabled
    public list<Map_Sub_Region__c> subRegions {get;set;}
      @auraEnabled
    public Region__c region {get;set;}
    
    @auraEnabled(cacheable=true)
    public static leadCmpController fetchLead(string leadId){
        if (String.isEmpty(leadId)) {
            return null;
        }
        lead lead =[select id ,Region__c,Region__r.Name from lead where Id=:leadId];
        if(lead.Region__c !=null){
            list<Map_Sub_Region__c> subRegions = new list<Map_Sub_Region__c>();
            leadCmpController l = new leadCmpController();
            l.region =[select Id,Name from Region__c where Id=:lead.Region__c];
            l.subRegions =[select Id,name,Sales_Engineer__c,Sales_Engineer__r.Name,ASM__c,ASM__r.Name from Map_Sub_Region__c where Region__c=:lead.Region__c and Active__c=true];
          return l;
        }else{
           return null;
        }
       
    }

  @auraEnabled
  public static void leadAssignment(string leadOwnerId,string leadId){
    lead ld = new lead();
        ld.Id = leadId;
          ld.ownerId =leadOwnerId;        
    update ld;
  }
}