force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Expense_Approver_L1__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approver_L1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Expenses3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Finance_Department_Approver__c.field-meta.xml
<CustomField>
    <fullName>Expense_Finance_Department_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense  Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Expenses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/General_Settings__c.object-meta.xml
<CustomObject>
    <label>General Setting</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>General Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Settings__c/fields/Expense_Level_1_Approver__c.field-meta.xml
<CustomField>
    <fullName>Expense_Level_1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Level 1 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Expense_Level_2_Approver__c.field-meta.xml
<CustomField>
    <fullName>Expense_Level_2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Level 2 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settingsr68A</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExpenseTriggerHandler.cls
public with sharing class ExpenseTriggerHandler {

    public static void afterInsert(List<Expense__c> newExpenses) {
   if (newExpenses == null || newExpenses.isEmpty()) {
            return;
        }
        // Fetch General Settings safely
        List<General_Settings__c> settingsList = [SELECT Id, Expense_Level_1_Approver__c,   Expense_Level_2_Approver__c  FROM General_Settings__c LIMIT 1];
       list<Id> userList = new list<Id>();
        map<Id,Id> userManagerMap = new map<Id,Id>();
        for (Expense__c exp : newExpenses) {
            userList.add(exp.OwnerId);
        }
         list<user> expOwnerList =[select id,ManagerId  from user where Id in:userList];
        if(!expOwnerList.isEmpty()){
            for(user u : expOwnerList){
                if(u.ManagerId != null){
                userManagerMap.put(u.Id,u.ManagerId);    
                }
            }
        }
        // Apply approvers
        for (Expense__c exp : newExpenses) {
 
            if(userManagerMap.containsKey(exp.OwnerId)){
                exp.Expense_Approver_L1__c = userManagerMap.get(exp.OwnerId);
            }else {
                if (settingsList[0].Expense_Level_1_Approver__c != null) 
                exp.Expense_Approver_L1__c =  settingsList[0].Expense_Level_1_Approver__c;
            }
         
            if (settingsList[0].Expense_Level_2_Approver__c != null) {
                exp.Expense_Finance_Department_Approver__c =settingsList[0].Expense_Level_2_Approver__c;
            }
        }
    }
}